[tool.poetry]
name = "poptimizer"
version = "0.1.0"
description = "Portfolio optimization"
authors = ["WLMike <wlmike@gmail.com>"]
license = "The Unlicense"
readme = "README.md"
repository = "https://github.com/WLM1ke/poptimizer"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas = "^1.4.3"
motor = "^3.0.0"
aiomoex = "^2.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.971"
pytest = "^7.1.2"
wemake-python-styleguide = "^0.16.1"
pytest-cov = "^3.0.0"
black = {extras = ["d"], version = "^22.6.0"}

[tool.mypy]
ignore_missing_imports = true

disallow_any_explicit = true
disallow_any_generics = true
disallow_subclassing_any = true

disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

no_implicit_optional = true
strict_optional = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

show_none_errors = true
ignore_errors = false

allow_untyped_globals = false
allow_redefinition = false
implicit_reexport = false
strict_equality = true

warn_unused_configs = true

[[tool.mypy.overrides]]
module = "*.tests.*"
ignore_errors = true

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
omit = ["*/tests/*"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
