[tool.poetry]
name = "poptimizer"
version = "3.0.0"
description = "Portfolio optimization"
authors = ["WLMike <wlmike@gmail.com>"]
license = "The Unlicense"
readme = "README.md"
repository = "https://github.com/WLM1ke/poptimizer"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
motor = "^3.0.0"
aiomoex = "^2.0.0"
openpyxl = "^3.0.10"
pydantic = "^1.9.2"
uvloop = "^0.16.0"
aiofiles = "^22.1.0"
lxml = "^4.9.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.971"
pytest = "^7.1.2"
wemake-python-styleguide = "^0.16.1"
pytest-cov = "^3.0.0"
black = {extras = ["d"], version = "^22.6.0"}

[tool.mypy]
plugins = [
    "pydantic.mypy"
]

strict = true
ignore_missing_imports = true
warn_unreachable = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:"]
omit = ["*/tests/*"]

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
