[tool.poetry]
name = "poptimizer"
version = "0.1.0"
description = "Оптимизация долгосрочного портфеля акций"
authors = ["Михаил aka https://github.com/WLM1ke"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.4.3"
numpy = "^1.23.1"
scipy = "^1.8.1"
scikit-learn = "^1.1.1"
torch = "^1.12.0"
tqdm = "^4.64.0"
openpyxl = "^3.0.10"
XlsxWriter = "^3.0.3"
lxml = "^4.9.1"
reportlab = "^3.6.11"
matplotlib = "^3.5.2"
pymongo = "^4.1.1"
motor = "^3.0.0"
aiomoex = "^2.0.0"
beautifulsoup4 = "^4.11.1"
aiohttp = "^3.8.1"
pyppeteer = "^1.0.2"
certifi = "^2022.6.15"
psutil = "^5.9.1"
PyYAML = "^6.0"
typer = "^0.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
